<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hockey_robot">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="1.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="tackers_radius" value="0.86" /> <!-- Link 1 -->
  <xacro:property name="tackers_height" value="0.1" />
  <xacro:property name="camera_height" value="1.5" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="sonar_length" value="0.07" /> 
  <xacro:property name="sonar_width" value="0.01" /> 
  <xacro:property name="sonar_height" value="0.02" /> 
  <xacro:property name="sonar_link" value="0.1" /> 
  <xacro:property name="pusher_height" value="0.02" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="pusher_radius" value="0.045" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find hockey_robot_description)/urdf/hockey_robot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find hockey_robot_description)/urdf/materials.xacro" />

  
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.8" rpy="0 0 0"/>
  </joint>
  
  <link name="base_link">
    <visual>
      <geometry>
        <mesh filename="package://hockey_robot_description/meshes/hockeytablev2.dae"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.46 -0.7 -0.8"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://hockey_robot_description/meshes/hockeytablev2.dae"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.46 -0.7 -0.8"/>
    </collision>
    <inertial>
      <mass value="80"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>


  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 0 0" />
    <!--rigin xyz="0 1 ${height3 - axel_offset*2}" rpy="0 0 0"/-->
    <origin xyz="0 0 ${camera_height}" rpy="0 ${pi/2} 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <!-- Sonar -->
  <link name="sonar_1">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="${sonar_width} ${sonar_length} ${sonar_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="${sonar_width} ${sonar_length} ${sonar_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  <joint name="sonar_1_joint" type="fixed">
    <axis xyz="0 0 0" />
    <!--rigin xyz="0 1 ${height3 - axel_offset*2}" rpy="0 0 0"/-->
    <origin xyz="-0.15 -0.95 ${sonar_height/2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="sonar_1"/>
  </joint>

  <link name="sonar_2">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="${sonar_width} ${sonar_length} ${sonar_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="${sonar_width} ${sonar_length} ${sonar_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  <joint name="sonar_2_joint" type="fixed">
    <axis xyz="0 0 0" />
    <!--rigin xyz="0 1 ${height3 - axel_offset*2}" rpy="0 0 0"/-->
    <origin xyz="0.15 0.95 ${sonar_height/2}" rpy="0 0 ${pi}"/>
    <parent link="base_link"/>
    <child link="sonar_2"/>
  </joint>

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>

  <link name="camera_link_optical">
  </link>

  <link name="horizon_track_1">
    <visual>
      <geometry>
        <box size="${width} 0.01 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${width} 0.05 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  <joint name="base_to_horizon_track_1" type="prismatic">
    <axis xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="horizon_track_1"/>
    <limit effort="1000.0" lower="0" upper="${tackers_radius}" velocity="0.5"/>
    <origin xyz="0 ${-tackers_radius} ${tackers_height}"/>
  </joint>


  <link name="pusher_1">
    <visual>
      <geometry>
        <cylinder length="${pusher_height}" radius="${pusher_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${pusher_height}" radius="${pusher_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  <joint name="horizon_track_1_to_pusher_1" type="prismatic">
    <axis xyz="1 0 0"/>
    <parent link="horizon_track_1"/>
    <child link="pusher_1"/>
    <limit effort="1000.0" lower="-0.5" upper="0.5" velocity="0.5"/>
    <origin xyz="0 0 -${tackers_height-pusher_height/2}"/>
  </joint>

  <link name="horizon_track_2">
    <visual>
      <geometry>
        <box size="${width} 0.01 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${width} 0.05 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  <joint name="base_to_horizon_track_2" type="prismatic">
    <axis xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="horizon_track_2"/>
    <limit effort="1000.0" lower="0" upper="${tackers_radius}" velocity="0.5"/>
    <origin xyz="0 ${tackers_radius} ${tackers_height}" rpy="0 0 ${pi}"/>
  </joint>


  <link name="pusher_2">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.045"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.02" radius="0.045"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  <joint name="horizon_track_2_to_pusher_2" type="prismatic">
    <axis xyz="1 0 0"/>
    <parent link="horizon_track_2"/>
    <child link="pusher_2"/>
    <limit effort="1000.0" lower="-0.5" upper="0.5" velocity="0.5"/>
    <origin xyz="0 0 -${tackers_height-pusher_height/2}"/>
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_horizon_track_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="horizon_track_1_to_pusher_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_horizon_track_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="horizon_track_2_to_pusher_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>
