<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pusher">
  <xacro:property name="width" value="1.4" />
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  
  <link name="base_link">
    <visual>
      <geometry>
        <box size="1 0.1 1"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="1 0.1 1"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="80"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <link name="horizon_track">
    <visual>
      <geometry>
        <box size="${width} 0.05 0.01"/>
      </geometry>
      <origin rpy="0 0 1.57075" xyz="0 ${width/2} 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${width} 0.05 0.01"/>
      </geometry>
      <origin rpy="0 0 1.57075" xyz="0 ${width/2} 0"/>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  <joint name="base_to_horizon_track" type="prismatic">
    <parent link="base_link"/>
    <child link="horizon_track"/>
    <limit effort="1000.0" lower="-0.5" upper="0.5" velocity="0.5"/>
    <origin xyz="0 0 0.5"/>
  </joint>


  <link name="pusher">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.045"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.02" radius="0.045"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  <joint name="horizon_track_to_pusher" type="prismatic">
    <axis xyz="0 1 0"/>
    <parent link="horizon_track"/>
    <child link="pusher"/>
    <limit effort="1000.0" lower="-0.5" upper="0.5" velocity="0.5"/>
    <origin xyz="0 ${width/2} -0.1"/>
  </joint>

  <link name="left_leg">
    <visual>
      <geometry>
        <box size="1 0.1 1"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="1 0.1 1"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="80"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  <joint name="base_to_left_leg" type="fixed">
    <parent link="base_link"/>
    <child link="left_leg"/>
    <origin xyz="0 ${width} 0"/>
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_horizon_track">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="horizon_track_to_pusher">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

</robot>
